### ISSUE TITLE
[proposal] Move the plugin into dedicated GitHub org

### ISSUE THREAD

**Issue by eshepelyuk** [traefik-plugins/traefik-jwt-plugin#57]
Hello @blagerweij 

I am maintaining few more Traefik plugins and recently decided to try organizing a central place for them and maybe in future other plugins to

For this purpose I've created a new GH organization
where I plan to move current plugins I am currently maintaining.
https://github.com/traefik-plugins

So I'd like to ask if you mind to donate \ move this plugin to that organization as well ?
I could give you all required permission to keep maintaing the code.

WDYT ? Thnx in advance.

**Comment by blagerweij** [comment]
@eshepelyuk sure, no problem. Can you facilitate the move, or do you need something ?

**Comment by eshepelyuk** [comment]
Hello

To tranfer a repo plz nabigate here 
https://github.com/team-carepay/traefik-jwt-plugin/settings

And in the bottom there will be *Transfer* button.
![Screenshot_2023-12-14-21-06-37-545~2](https://github.com/team-carepay/traefik-jwt-plugin/assets/1279477/5251ff6b-567f-4c80-b390-13fc442d811f)

**Comment by eshepelyuk** [comment]
Thank you
