### ISSUE TITLE
Installation error when using README code

### ISSUE THREAD

**Issue by aldosr** [traefik-plugins/traefik-jwt-plugin#64]
Using the code provided in the README with helm installation gave me the following error:
`
ERROR: plugin enabled is missing moduleName/version keys !`

Even if I use the latest version (i.e. v0.7.0).

However, it works like a charm when I use the code provided in the Pluging catalog:
https://plugins.traefik.io/plugins/62947304108ecc83915d7782/jwt-access-policy

Is this behavior expected or I'm missing something?

**Comment by eshepelyuk** [comment]
Just updated README, it had incorrect version. Could you check again ?

**Comment by aldosr** [comment]
Works fine!
